#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import os.path
import sys
WORK_DIR = '/var/workers'
PATH_WITH_EN_WORKERS = WORK_DIR+'/workers-enabled'
PATH_WITH_PIDS = WORK_DIR+'/pids'
DEFAULT_USER_AND_GROUP = 'www-data'
os.chdir(WORK_DIR)
def main():
    if (len(sys.argv) < 2):
	viewhelp()
	exit()
    if (sys.argv[1] == 'start'):
	start(force=False)
    if (sys.argv[1] == 'force-start'):
	start(force=True)	
    elif (sys.argv[1] == 'stop'): 
	stop(force=False)
    elif (sys.argv[1] == 'force-stop'): 
	stop(force=True)
    elif (sys.argv[1] == 'restart'): 
	stop()
	start()
    else:
	viewhelp()

def start(force=False):
    print "Start workers.....\n"
    files = os.listdir(PATH_WITH_EN_WORKERS)
    for  f in files:
	if (os.path.exists(PATH_WITH_PIDS+'/'+f+'.pid') ):
	    print f+"... seem allready running (use force-start)\n"
	    if (not force):
		continue
	os.system('su '+DEFAULT_USER_AND_GROUP+' -c '+PATH_WITH_EN_WORKERS+'/'+f)
	print f+"\n"

def stop(force=False):
    print "Stop workers......\n"
    pid_files = os.listdir(PATH_WITH_PIDS)
    for pid_file in pid_files:
	add_kill_param = ''
	if (force):
	    add_kill_param = ' -9 '
	pid = open(pid_file).read()
	os.system('kill '+add_kill_param+' '+pid)
def viewhelp():
    print "\n\n(start|force-start|stop|force-stop|restart)\n\n"

if (__name__=="__main__"):
    main()